### ISSUE TITLE
安装monaco-pytho-lsp之后在执行python language_ext.py时报错No such file or directory: 'pyls'

### ISSUE THREAD

**Issue by yuankang134** [Wiihame/Monaco-python-lsp#17]
Uncaught exception GET /python (xx.xx.xxx.x)
HTTPServerRequest(protocol='http', host='xx.xx.xxx.x:3001', method='GET', uri='/python', version='HTTP/1.1', remote_ip='xx.xx.xxx.x')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/tornado/websocket.py", line 942, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/root/code/Monaco-python-lsp/python-server/langserver_ext.py", line 22, in open
    proc = process.Subprocess(
  File "/usr/local/python3/lib/python3.9/site-packages/tornado/process.py", line 240, in __init__
    self.proc = subprocess.Popen(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyls'

**Comment by Sakura1609** [comment]
I got the same error. Have you solved it?

**Comment by jiajiawei** [comment]
我直接装了全套, 能解决  `pip install python-language-server[all]`

**Comment by Germxu** [comment]
> 我直接装了全套, 能解决 `pip install python-language-server[all]`

谢谢解决了我的问题, 虽然我的报错的是pyls包的代码问题, 我检查了这个pyls包的代码是python2的
